from selenium.webdriver.common.by import By

TOP_ORDER_BUTTON = [By.CLASS_NAME, 'Button_Button__ra12g']
BOTTOM_ORDER_BUTTON = [By.XPATH, './/div[@class="Home_FinishButton__1_cWm"]/button']
NAME_FIELD = [By.XPATH, './/input[contains(@placeholder, "Имя")]']
SURNAME_FIELD = [By.XPATH, './/input[contains(@placeholder, "Фамилия")]']
ADDRESS_FIELD = [By.XPATH, './/input[contains(@placeholder, "Адрес")]']
STATION_FIELD = [By.XPATH, './/input[contains(@placeholder, "Станция")]']
STATION_DROPDOWN_LIST = [By.CLASS_NAME, 'select-search__options']
PHONE_FIELD = [By.XPATH, './/input[contains(@placeholder, "Телефон")]']
CONTINUE_BUTTON = [By.XPATH, './/button[contains(@class, "Button_Middle__1CSJM")]']
BACK_BUTTON = [By.XPATH, './/button[text()="Назад"]']
DATE_FIELD = [By.XPATH, './/input[contains(@placeholder, "Когда")]']
DATEPICKER = [By.CLASS_NAME, 'react-datepicker__month-container']
DATE_9_BUTTON = [By.XPATH, './/div[text()="9"]']
DATE_10_BUTTON = [By.XPATH, './/div[text()="10"]']
PERIOD_FIELD = [By.CLASS_NAME, 'Dropdown-placeholder']
PERIOD_MENU = [By.CLASS_NAME, 'Dropdown-menu']
TWO_DAYS_PERIOD_BUTTON = [By.XPATH, './/div[text()="двое суток"]']
THREE_DAYS_PERIOD_BUTTON = [By.XPATH, './/div[text()="трое суток"]']
CHECKBOX_BLACK = [By.ID, 'black']
CHECKBOX_GREY = [By.ID, 'grey']
COMMENT_FIELD = [By.XPATH, './/input[contains(@placeholder, "Комментарий")]']
SAVE_BUTTON = [By.XPATH, './/div[@class="Order_Buttons__1xGrp"]/button[text()="Заказать"]']
CONFIRM_MODAL = (By.CLASS_NAME, 'Order_Modal__YZ-d3')
CONFIRM_BUTTON = [By.XPATH, './/button[text()="Да"]']
SUCCESS_WINDOW = [By.CLASS_NAME, 'Order_ModalHeader__3FDaJ']
VIEW_STATUS_BUTTON = [By.XPATH, './/button[text()="Посмотреть статус"]']
YA_BUTTON = [By.CLASS_NAME, 'Header_LogoYandex__3TSOI']
HOME_BUTTON = [By.CLASS_NAME, 'Header_LogoScooter__3lsAR']